blank_issues_enabled: false
contact_links:
  - name: ↗️ Terragraph NMS
    url: https://github.com/terragraph/tgnms
    about: For tickets regarding the Terragraph NMS, use their issue tracker instead.
